### ISSUE TITLE
Figma Design: Login and Sign up

### ISSUE THREAD

**Issue by dipanshuhappy** [Buggermenot/KitchHub#2]

**Comment by manya7917** [comment]
Mobile view login and sign-in page
https://user-images.githubusercontent.com/97101872/187986868-ff694469-0720-4121-b4d0-58676b50642c.jpeg
https://user-images.githubusercontent.com/97101872/187986889-6b769c03-9db3-49ac-a178-1c576955c8e9.jpeg
@dipanshuhappy @Buggermenot @Deltanite483

**Comment by dipanshuhappy** [comment]
So this is the desktop view
![Screenshot (117)](https://user-images.githubusercontent.com/58115782/187989555-bf67fd4a-6545-4e01-ad6e-21d1ea7131b6.png)
![Capture](https://user-images.githubusercontent.com/58115782/187989746-8722e196-e041-4c30-adb3-9234df90d693.PNG)
 Will find a place to add that logo in the desktop view too... and also fix that logo gray background too 
@jayeshkumar1951  @manya7917 @Buggermenot @Deltanite483

**Comment by jayeshkumar1951** [comment]
Excellent work Dipanshu and Manya!

**Comment by jayeshkumar1951** [comment]
Please add a 'Forgot password' button.

Also, when they sign up, shouldn't we be collecting their name? Otherwise, what will we address them as on the next page(dashboard, home page, 'we would like to know you more'), surely not, 'Hey User' or 'Hey Foodie'....wouldn't have that personal touch.

**Comment by dipanshuhappy** [comment]
Yeah we will collect there name and other info on a different page

**Comment by dipanshuhappy** [comment]
> Please add a 'Forgot password' button.
> 
> Also, when they sign up, shouldn't we be collecting their name? Otherwise, what will we address them as on the next page(dashboard, home page, 'we would like to know you more'), surely not, 'Hey User' or 'Hey Foodie'....wouldn't have that personal touch.

i will add the forgot button today ..

**Comment by jayeshkumar1951** [comment]
> Yeah we will collect there name and other info on a different page

Collect it when they sign up, why on a different page?

**Comment by dipanshuhappy** [comment]
They shouldn't have a long form... When they sign up initially... Let the long form come later

**Comment by dipanshuhappy** [comment]
@jayeshkumar1951  i havve the required changes to login and sign up
