### ISSUE TITLE
Decide a name

### ISSUE THREAD

**Issue by dipanshuhappy** [Buggermenot/KitchHub#7]
If you have any name suggestion please put it down the comment ... @Buggermenot  @manya7917  @Deltanite483

**Comment by dipanshuhappy** [comment]
We need a name that is catchy ... maybe food related ....

**Comment by dipanshuhappy** [comment]
jdlgl

**Comment by jayeshkumar1951** [comment]
Maybe something on the lines of, our platform being a heaven for foodies(well, not just foodies, anyone who ever considers exploring different food options).
...What if we use a sanskrit or hindi term....just for the desi effect....even when we go global, we could be like, we are exporting our 'Indianness'.

**Comment by dipanshuhappy** [comment]
so something like Foodhub or foodgyan

**Comment by jayeshkumar1951** [comment]
I like Kitchub though, just saying 😁
